Auth/urls.py
from django.urls import path
from .views import *

app_name = 'Auth'
urlpatterns = [
    path('users/login/', UserLogin.as_view(), name='UserLogin'),
    path('users/logout/', UserLogout.as_view(), name='UserLogout'),
    path('users/register/', RegisterUser.as_view(), name='RegisterUser'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('permissions/<int:pk>/', permissions, name='permissions'),
    path('login/as/<int:pk>/', login_as, name='login_as'),
    path('password/', change_password, name='change_password'),
    path('setting/', account_setting, name='account_setting'),
    path('users/<int:pk>/reset_password/', PasswordReset.as_view(), name='PasswordReset'),
    path('employee/<int:pk>/user/create/', create_user_for_employee, name='create_user_for_employee'),
]

Core/urls.py
from .views import *
from django.urls import path

app_name = 'Core'
urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('change_log/', ChangeLog.as_view(), name='ChangeLog'),
    path('fix/', fix, name='fix'),
    path('update/', update, name='update'),
    
    
]

HR/urls.py
from .views import *
from django.urls import path

app_name = 'HR'
urlpatterns = [
    path('employees/', EmployeeList.as_view(), name='EmployeeList'),
    path('employees/new/', EmployeeCreate.as_view(), name='EmployeeCreate'),
    path('employees/<int:pk>/edit/', EmployeeUpdate.as_view(), name='EmployeeUpdate'),
    path('employees/<int:pk>/delete/', EmployeeDelete.as_view(), name='EmployeeDelete'),
    path('employees/<int:pk>/view/', EmployeeDetail.as_view(), name='EmployeeDetail'),
    path('employees/<int:pk>/upload/', UploadFile.as_view(), name='UploadFile'),
    path('employees/files/view/<int:pk>/', ViewFile.as_view(), name='ViewFile'),

    ]

ONERP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
#done merge 


urlpatterns = [
    path('admincp/', admin.site.urls),
    path('', include('Website.urls')),
    path('admin/', include('Core.urls')),
    path('auth/', include('Auth.urls')),
    path('products/', include('Products.urls')),
    path('branches/', include('Branches.urls')),
    path('treasuries/', include('Treasuries.urls')),
    path('customers/', include('Customers.urls')),
    path('partners/', include('Partners.urls')),
    path('tasks/', include('Tasks.urls')),
    #path('prices', include('Prices.urls')),
    path('invoices_maged/', include('InvoicesMaged.urls')),
    path('chat/', include('Chat.urls')),    
    path('hr/', include('HR.urls')),
    path('barcode/', include('Barcode.urls')),
    path('invoices/', include('Invoices.urls')),
    path('select2/', include('django_select2.urls')),
    path('reports/', include('Reports.urls')),
    path('calendar/', include('Calendar.urls')),
    path('maintenance/', include('Maintenance.urls')),
    path('projects/', include('Projects.urls')),
    path('technicians/', include('Technicians.urls')),
    path('setup/', include('Setting.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view, name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view, name='password_reset_done'),
    path('reset/<slug:uidb64>/<slug:token>/', auth_views.PasswordResetConfirmView.as_view, name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view, name='password_reset_complete'),
    
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Products/urls.py
from .views import *
from django.urls import path

app_name = 'Products'
urlpatterns = [
    path('main_categories/', MainCategoryList.as_view(), name='MainCategoryList'),
    path('main_categories/new/', MainCategoryCreate.as_view(), name='MainCategoryCreate'),
    path('main_categories/trash/', MainCategoryTrashList.as_view(), name='MainCategoryTrashList'),
    path('main_categories/<int:pk>/edit/', MainCategoryUpdate.as_view(), name='MainCategoryUpdate'),
    path('main_categories/<int:pk>/delete/', MainCategoryDelete.as_view(), name='MainCategoryDelete'),
    
    path('sub_categories/', SubCategoryList.as_view(), name='SubCategoryList'),
    path('sub_categories/new/', SubCategoryCreate.as_view(), name='SubCategoryCreate'),
    path('sub_categories/trash/', SubCategoryTrashList.as_view(), name='SubCategoryTrashList'),
    path('sub_categories/<int:pk>/edit/', SubCategoryUpdate.as_view(), name='SubCategoryUpdate'),
    path('sub_categories/<int:pk>/delete/', SubCategoryDelete.as_view(), name='SubCategoryDelete'),

    path('manufactures/', ManufactureList.as_view(), name='ManufactureList'),
    path('manufactures/new/', ManufactureCreate.as_view(), name='ManufactureCreate'),
    path('manufactures/trash/', ManufactureTrashList.as_view(), name='ManufactureTrashList'),
    path('manufactures/<int:pk>/edit/', ManufactureUpdate.as_view(), name='ManufactureUpdate'),
    path('manufactures/<int:pk>/delete/', ManufactureDelete.as_view(), name='ManufactureDelete'),

    path('brands/', BrandList.as_view(), name='BrandList'),
    path('brands/new/', BrandCreate.as_view(), name='BrandCreate'),
    path('brands/trash/', BrandTrashList.as_view(), name='BrandTrashList'),
    path('brands/<int:pk>/edit/', BrandUpdate.as_view(), name='BrandUpdate'),
    path('brands/<int:pk>/delete/', BrandDelete.as_view(), name='BrandDelete'),

    path('units/', UnitList.as_view(), name='UnitList'),
    path('units/new/', UnitCreate.as_view(), name='UnitCreate'),
    path('units/trash/', UnitTrashList.as_view(), name='UnitTrashList'),
    path('units/<int:pk>/edit/', UnitUpdate.as_view(), name='UnitUpdate'),
    path('units/<int:pk>/delete/', UnitDelete.as_view(), name='UnitDelete'),

    path('products/', ProductList.as_view(), name='ProductList'),
    path('products/new/', ProductCreate.as_view(), name='ProductCreate'),
    path('products/add/', product_create, name='product_create'),
    path('products/trash/', ProductTrashList.as_view(), name='ProductTrashList'),
    path('products/<int:pk>/edit/', ProductUpdate.as_view(), name='ProductUpdate'),
    path('products/<int:pk>/delete/', ProductDelete.as_view(), name='ProductDelete'),
    path('products/<int:pk>/show/', ProductCard.as_view(), name='ProductCard'),
    path('products/<int:pk>/add_content/', GroupedProductCreate.as_view(), name='GroupedProductCreate'),
    path('products/<int:pk>/note_update/', ProductNoteUpdate.as_view(), name='ProductNoteUpdate'),

    path('grouped_product/<int:pk>/<int:ppk>/edit/', GroupedProductUpdate.as_view(), name='GroupedProductUpdate'),
    path('grouped_product/<int:pk>/<int:ppk>/delete/', GroupedProductDelete.as_view(), name='GroupedProductDelete'),

    #########################################

    path('prices/<int:pk>/add_content/', PricesProductCreate.as_view(), name='PricesProductCreate'),
    path('prices_product/<int:pk>/<int:ppk>/edit/', PricesProductUpdate.as_view(), name='PricesProductUpdate'),
    path('prices_product/<int:pk>/<int:ppk>/delete/', PricesProductDelete.as_view(), name='PricesProductDelete'),
    path('prices_product/<int:pk>/stop/', PricesProductStop.as_view(), name='PricesProductStop'),
    path('prices_product/<int:pk>/active/', PricesProductActive.as_view(), name='PricesProductActive'),
    path('prices_product/editAll/', PricesProductEditAll, name='PricesProductEditAll'),
    path('products/<int:pk>/editPrice/', ProductPriceUpdate.as_view(), name='ProductPriceUpdate'),

    path('main_prices/', MainPricesList.as_view(), name='MainPricesList'),
    path('main_prices/new/', MainPricesListCreate.as_view(), name='MainPricesListCreate'),
    path('main_prices/trash/', MainPricesTrashList.as_view(), name='MainPricesTrashList'),
    path('main_prices/<int:pk>/edit/', MainPricesListUpdate.as_view(), name='MainPricesListUpdate'),
    path('main_prices/<int:pk>/delete/', MainPricesListDelete.as_view(), name='MainPricesListDelete'),
    path('main_prices/<int:pk>/show/', PricesListCard.as_view(), name='PricesListCard'),
    path('prices_product_list/editAll/', PricesProductListEditAll, name='PricesProductListEditAll'),

    path('product_units/<int:pk>/add_unit/', ProductUnitCreate.as_view(), name='ProductUnitCreate'),
    path('product_units/<int:pk>/edit/', ProductUnitUpdate.as_view(), name='ProductUnitUpdate'),
    path('product_units/<int:pk>/delete/', ProductUnitDelete.as_view(), name='ProductUnitDelete'),


    path('customerprices/<int:pk>/<int:ppk>/edit/', CustomerPricesUpdate.as_view(), name='CustomerPricesUpdate'),
    path('customerprices/<int:pk>/<int:ppk>/delete/', CustomerPricesDelete.as_view(), name='CustomerPricesDelete'),

]

Website/urls.py
from django.urls import path
from .views import *


app_name = 'Website'
urlpatterns = [
    path('', HomePage.as_view(), name='HomePage'),
    path('shop/', Shop.as_view(), name='Shop'),
    path('<int:pk>/products/', ProductList.as_view(), name='ProductList'),
    path('product/<int:pk>/', ProductView.as_view(), name='ProductView'),
    path('add_to_cart/', AddToCart.as_view(), name='AddToCart'),
    path('search/', Search.as_view(), name='Search')
]

Website/models.py
from django.db import models


# Create your models here.
class Tag(models.Model):
    word = models.CharField(max_length=35)
    slug = models.CharField(max_length=250)
    created_at = models.DateTimeField(auto_now_add=False)

    def __str__(self):
        return self.word


class HomePageSlider(models.Model):
    image = models.ImageField(verbose_name='الصورة')
    title = models.CharField(max_length=128, verbose_name='العنوان', null=True, blank=True)
    description = models.TextField(verbose_name='تعليق', null=True, blank=True)
    url = models.URLField(verbose_name='تحويل إلي', null=True, blank=True)
    disabled = models.BooleanField(default=False, verbose_name='تعطيل')

    def __str__(self):
        return str(self.id)


class Page(models.Model):
    title = models.CharField(max_length=128, verbose_name='اسم الصفحة')
    content = models.TextField(verbose_name='محتوي الصفحة')
    tags = models.ManyToManyField(Tag, blank=True, verbose_name='الكلمات الدلالية')
    parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.SET_NULL, verbose_name='تحت صفحة')
    add_to_menu = models.BooleanField(default=False, verbose_name='إضافة للقائمة الرئيسية')

    def __str__(self):
        return self.title


class WebsiteSetting(models.Model):
    primary_color = models.CharField(null=True, blank=True, default='#000000', verbose_name='اللون الاساسي',
                                     max_length=7)
    primary_text_color = models.CharField(null=True, blank=True, default='#ffffff',
                                          verbose_name='لون النص في اللون الاساسي', max_length=7)
    title = models.CharField(max_length=128, default='ON-Link', verbose_name="اسم الموقع")
    logo = models.ImageField(null=True, blank=True, verbose_name='الشعار')

    def __str__(self):
        return self.title

Website/forms.py
from django import forms
from .models import *
from Invoices.models import *


class AddToCartForm(forms.ModelForm):
    class Meta:
        model = InvoiceItem
        fields = ['quantity']

Website/views.py
from django.urls import reverse_lazy
from django.urls import reverse_lazy
from django.views.generic import *
from Invoices.models import *
from .forms import *
from django.db.models import Q


# Create your views here.
class HomePage(TemplateView):
    template_name = 'Website/homepage.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        setting = WebsiteSetting.objects.get_or_create(id=1)
        setting = WebsiteSetting.objects.get(id=1)
        context['setting'] = setting
        homepage_slider = HomePageSlider.objects.all()
        context['slides'] = homepage_slider
        context['navbar_pages'] = Page.objects.filter(add_to_menu=True)
        context['main_categories'] = MainCategory.objects.filter(deleted=False)
        return context


class Shop(TemplateView):
    template_name = 'Website/shop.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        setting = WebsiteSetting.objects.get_or_create(id=1)
        setting = WebsiteSetting.objects.get(id=1)
        context['setting'] = setting
        context['main_categories'] = MainCategory.objects.filter(deleted=False)
        return context


class ProductView(DetailView):
    model = Product
    template_name = 'Website/ProductView.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        setting = WebsiteSetting.objects.get_or_create(id=1)
        setting = WebsiteSetting.objects.get(id=1)
        context['setting'] = setting
        context['main_categories'] = MainCategory.objects.filter(deleted=False)
        return context


class ProductList(ListView):
    model = Product
    template_name = 'Website/productList.html'
    paginate_by = 100

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        setting = WebsiteSetting.objects.get_or_create(id=1)
        setting = WebsiteSetting.objects.get(id=1)
        context['setting'] = setting
        context['main_categories'] = MainCategory.objects.filter(deleted=False)
        return context

    def get_queryset(self):
        queryset = Product.objects.filter(deleted=False)
        sub_category_id = self.kwargs['pk']
        queryset = queryset.filter(sub_category__id=sub_category_id)
        return queryset


class Search(ProductList):
    def get_queryset(self):
        queryset = Product.objects.filter(deleted=False)
        if self.request.GET.get('q'):
            s = self.request.GET.get('q')
            queryset = queryset.filter(
                Q(name__icontains=s) |
                Q(description__icontains=s) |
                Q(brand__name__icontains=s) |
                Q(manufacture__name__icontains=s) |
                Q(sub_category__name__icontains=s) |
                Q(sub_category__main_category__name__icontains=s)
            )
        if self.request.GET.get('sub_category'):
            queryset = queryset.filter(sub_category__id=self.request.GET.get('sub_category'))
        if self.request.GET.get('main_category'):
            queryset = queryset.filter(sub_category__main_category__id=self.request.GET.get('main_category'))
        if self.request.GET.get('brand'):
            queryset = queryset.filter(brand__id=self.request.GET.get('brand'))
        return queryset


def get_user_invoice(request):
    if request.user.invoice_set.filter(saved=False).count > 0:
        opened_invoice = request.user.invoice_set.filter(saved=False)[0]
    else:
        opened_invoice = Invoice()
        opened_invoice.creator = request.user
        opened_invoice.invoice_type = 3
        opened_invoice.save()
    return opened_invoice


class AddToCart(CreateView):
    model = InvoiceItem
    template_name = 'Website/form.html'
    form_class = AddToCartForm
    success_url = reverse_lazy('Website:Shop')

    def form_valid(self, form):
        product = Product.objects.get(id=self.request.GET.get('product'))
        invoice = get_user_invoice(self.request)
        item = form.save(commit=False)
        item.invoice = invoice
        item.product = product
        item.unit_price = product.sell_price
        item.total_price = item.unit_price * item.quantity
        item.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = Product.objects.get(id=self.request.GET.get('product'))
        context['title'] = 'إضافة' + str(product.name) + 'إلي سلة الشراء'
        setting = WebsiteSetting.objects.get_or_create(id=1)
        setting = WebsiteSetting.objects.get(id=1)
        context['setting'] = setting
        context['main_categories'] = MainCategory.objects.filter(deleted=False)
        return context

    def get_success_url(self):
        if self.request.POST.get('url'):
            return self.request.POST.get('url')
        else:
            return self.success_url


class MyOrders(ListView):
    model = Invoice
    template_name = 'Website/my_orders.html'
    paginate_by = 30

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        setting = WebsiteSetting.objects.get_or_create(id=1)
        setting = WebsiteSetting.objects.get(id=1)
        context['setting'] = setting
        context['main_categories'] = MainCategory.objects.filter(deleted=False)
        return context

    def get_queryset(self):
        queryset = Invoice.objects.filter(creator=self.request.user, invoice_type=3)
        return queryset


class MyCart(TemplateView):
    template_name = 'Website/cart.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        setting = WebsiteSetting.objects.get_or_create(id=1)
        setting = WebsiteSetting.objects.get(id=1)
        context['setting'] = setting
        context['main_categories'] = MainCategory.objects.filter(deleted=False)
        context['object'] = get_user_invoice(self.request)
        return context

Website/templates/Website/ProductView.html
{% extends 'Website/base.html' %}
{% block body %}
    <div class="col-lg-12">
        <h3>{{ object }}</h3>
    </div>
    <div class="col-lg-4 col-md-4">
        <div class="card">
            <div class="card-body">
                {% if object.image %}
                    <img src="{{ object.image.url }}" class="productImage">
                {% else %}
                    <i class="fa fa-5x fa-image productImage"></i>
                {% endif %}
            </div>
            <div class="card-footer">
                <div id="product_buttons">
                    {% if request.user.is_authenticated %}
                        <a href="{% url 'Website:AddToCart' %}?product={{ object.id }}"
                           class="btn btn-block btn-success bg-primary" data-toggle="modal"
                           data-target="#sub_modal">
                            <i class="fa fa-shopping-cart"></i>
                            إضافة للسلة
                        </a>
                    {% else %}
                        <a href="{% url 'Auth:UserLogin' %}"
                           class="btn btn-block btn-success bg-primary" data-toggle="modal"
                           data-target="#sub_modal">
                            <i class="fa fa-shopping-cart"></i>
                            إضافة للسلة
                        </a>
                    {% endif %}
                </div>
            </div>
        </div>
        <div id="tag_list">
            {% if object.brand %}
                <a href="{% url 'Website:Search' %}?brand={{ object.brand.id }}" class="badge bg-primary">{{ object.brand }}</a>
            {% endif %}
            {% if object.sub_category.main_category %}
                <a href="{% url 'Website:Search' %}?main_category={{ object.sub_category.main_category.id }}" class="badge bg-primary">{{ object.sub_category.main_category.name }}</a>
            {% endif %}
            {% if object.sub_category %}
                <a href="{% url 'Website:Search' %}?sub_category={{ object.sub_category.id }}" class="badge bg-primary">{{ object.sub_category.name }}</a>
            {% endif %}
        </div>
    </div>
    <div class="col-lg-8 col-md-8" style="text-align: right;">
        <h4>
            {{ object.sell_price|floatformat }} جنيه
        </h4>
        <br>
        {{ object.description|linebreaks }}
    </div>
{% endblock %}

Website/templates/Website/cart.html
{% extends 'Website/base.html' %}
{% block body %}
    <div class="col-lg-12 table-resposive">
        <table class="table table-hover">
            <thead>
            <td>#</td>
            <td>صورة</td>
            <td>المنتج</td>
            <td>الكمية</td>
            <td>سعر الوحدة</td>
            <td>إجمالي السعر</td>
            </thead>
            <tbody>
            {% for x in object.invoiceitem_set.all %}
                <tr>
                    <td>#</td>
                    <td>صورة</td>
                    <td>المنتج</td>
                    <td>الكمية</td>
                    <td>سعر الوحدة</td>
                    <td>إجمالي السعر</td>
                </tr>
            {% endfor %}
            <tr>
                <td></td>
                <td></td>
                <td>إجمالي</td>
                <td></td>
                <td></td>
                <td>{{ x.total_price }}</td>
            </tr>
            </tbody>
        </table>
    </div>
{% endblock %}

Website/templates/Website/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="{% url 'Website:HomePage' %}">
        {% if setting.logo %}
            <img src="{{ setting.logo.url }}" style="max-height: 60px;">
        {% else %}
            {{ setting.title }}
        {% endif %}
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <form class="form-inline my-2 my-lg-0" action="{% url 'Website:Search' %}" method="get">
            <input class="form-control mr-sm-2" type="search" placeholder="بحث ..." aria-label="Search" name="q">
        </form>

        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'Website:HomePage' %}">
                    <i class="fa fa-home"></i>
                    الرئيسية
                    <span class="sr-only">(current)</span>
                </a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                   data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    <i class="fa fa-shopping-cart"></i>
                    المتجر
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% for x in main_categories %}
                        {% if x.subcategory_set.all.count > 0 %}
                            <a class="dropdown-item dropdown-toggle" href="{% url 'Website:HomePage' %}">
                        {% else %}
                            <a class="dropdown-item" href="{% url 'Website:HomePage' %}">
                        {% endif %}
                    <i class="fa fa-th"></i>
                    {{ x.name }}
                    </a>
                        {% if x.subcategory_set.all.count > 0 %}
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                {% for y in x.subcategory_set.all %}
                                    <li>
                                        <a href="{% url 'Website:ProductList' y.id %}" class="dropdown-item">
                                            <i class="fa fa-list"></i>
                                            {{ y.name }}
                                        </a>
                                    </li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                    {% endfor %}
                </div>
            </li>
            {% if request.user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-user"></i>
                        {{ request.user }}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if request.user.is_staff %}
                            <a class="dropdown-item" href="{% url 'Core:index' %}" target="_blank">
                                <i class="fa fa-cog"></i>
                                لوحة تحكم الادارة
                            </a>
                            <div class="dropdown-divider"></div>
                        {% endif %}
                        <a class="dropdown-item" href="{% url 'Auth:account_setting' %}" data-toggle="modal"
                           data-target="#sub_modal">
                            <i class="fa fa-shopping-cart"></i>
                            سلة المشتريات
                        </a>
                        <a class="dropdown-item" href="{% url 'Auth:account_setting' %}" data-toggle="modal"
                           data-target="#sub_modal">
                            <i class="fa fa-clipboard-list"></i>
                            طلباتي
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'Auth:change_password' %}" data-toggle="modal"
                           data-target="#sub_modal">
                            <i class="fa fa-asterisk"></i>
                            تغيير كلمة السر
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'Auth:UserLogout' %}">
                            <i class="fa fa-power-off"></i>
                            تسجيل خروج
                        </a>
                    </div>
                </li>
            {% else %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-user"></i>
                        تسجيل
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'Auth:UserLogin' %}" data-toggle="modal"
                           data-target="#sub_modal">
                            <i class="fa fa-sign-in-alt"></i>
                            تسجيل دخول
                        </a>
                        <a class="dropdown-item" href="{% url 'Auth:RegisterUser' %}" data-toggle="modal"
                           data-target="#sub_modal">
                            <i class="fa fa-user-plus"></i>
                            حساب جديد
                        </a>
                    </div>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

Website/templates/Website/productList.html
{% extends 'Website/base.html' %}
{% block head %}
    <style>
        .pagination {
            position: absolute;
            text-align: center;
            align-content: center;
            align-self: center;
            align-items: center;
            bottom: 0px;
            margin: auto;
        }
    </style>
{% endblock %}
{% block body %}
    {% if object_list %}
        {% for product in object_list %}
            <div class="col-lg-3">
                <div class="card">
                <a href="{% url 'Website:ProductView' product.id %}">
                    <div class="card-header bg-primary">
                        {{ product.name }}
                    </div>
                    <div class="card-body">
                        {% if product.image %}
                            <img src="{{ product.image.url }}" class="productImage">
                        {% else %}
                            <i class="fa fa-5x fa-image productImage"></i>
                        {% endif %}
                        <div id="product_price" class="badge bg-primary">
                            {{ product.sell_price|floatformat }}
                            جنيه
                        </div>
                    </div>
                </a>
                    <div class="card-footer">
                        <div id="product_buttons">
                            {% if request.user.is_authenticated %}
                            <a href="{% url 'Website:AddToCart' %}?product={{ product.id }}"
                               class="btn btn-block btn-success bg-primary" data-toggle="modal"
                               data-target="#sub_modal">
                                <i class="fa fa-shopping-cart"></i>
                                إضافة للسلة
                            </a>
                            {% else %}
                            <a href="{% url 'Auth:UserLogin' %}"
                               class="btn btn-block btn-success bg-primary" data-toggle="modal"
                               data-target="#sub_modal">
                                <i class="fa fa-shopping-cart"></i>
                                إضافة للسلة
                            </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <div class="login-container">
            <span class="label label-alert">
                عفواً لا يوجد منتجات تحت هذا التصنيف
            </span>
        </div>
    {% endif %}


    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}">السابق</a>
                {% endif %}
                <span class="page-current">
                    صفحة {{ page_obj.number }} من {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">التالي</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
{% endblock %}

Website/templates/Website/shop.html
{% extends 'Website/base.html' %}

{% block body %}
    {% for x in main_categories %}
        <div class="col-lg-3 col-md-3 col-sm-6 align-items-stretch">
            <div class="card">
                <div class="card-body">
                    {% if x.image %}
                        <img src="{{ x.image.url }}" style="width:100%;">
                    {% else %}
                        <i class="fa fa-5x fa-th"></i>
                    {% endif %}
                </div>
                <div class="card-footer bg-primary">
                    {{ x.name }}
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}