Customers/urls.py
from .views import *
from django.urls import path

app_name = 'Customers'
urlpatterns = [
    path('categories/', CategoryList.as_view(), name='CategoryList'),
    path('categories/new/', CategoryCreate.as_view(), name='CategoryCreate'),
    path('categories/trash/', CategoryTrashList.as_view(), name='CategoryTrashList'),
    path('categories/<int:pk>/edit/', CategoryUpdate.as_view(), name='CategoryUpdate'),
    path('categories/<int:pk>/delete/', CategoryDelete.as_view(), name='CategoryDelete'),
    
    
    path('customers/', CustomerList.as_view(), name='CustomerList'),
    path('customers/new/', customer_create , name='CustomerCreate'),
    path('customers/trash/', CustomerTrashList.as_view(), name='CustomerTrashList'),
    path('customers/<int:pk>/edit/', CustomerUpdate.as_view(), name='CustomerUpdate'),
    path('customers/<int:pk>/delete/', CustomerDelete.as_view(), name='CustomerDelete'),
    path('customers/<int:pk>/view/', CustomerDetail.as_view(), name='CustomerDetail'),
    path('customers/<int:pk>/invoices/', CustomerInvoices.as_view(), name='CustomerInvoices'),
    path('customers/<int:pk>/calls/', CustomerCalls.as_view(), name='CustomerCalls'),


    path('customers_type/', CustomerTypeList.as_view(), name='CustomerTypeList'),
    path('customers_type/new/', CustomerTypeCreate.as_view(), name='CustomerTypeCreate'),
    path('customers_type/trash/', CustomerTypeTrashList.as_view(), name='CustomerTypeTrashList'),
    path('customers_type/<int:pk>/edit/', CustomerTypeUpdate.as_view(), name='CustomerTypeUpdate'),
    path('customers_type/<int:pk>/delete/', CustomerTypeDelete.as_view(), name='CustomerTypeDelete'),
    
   
    


    path('customers/<int:pk>/calls/add/', add_call, name='add_call'),
    path('customers/calls/<int:pk>/view/', CallDetail.as_view(), name='CallDetail'),

    path('call_reasons/', CallReasonList.as_view(), name='CallReasonList'),
    path('call_reasons/new/', CallReasonCreate.as_view(), name='CallReasonCreate'),
    path('call_reasons/trash/', CallReasonTrashList.as_view(), name='CallReasonTrashList'),
    path('call_reasons/<int:pk>/edit/', CallReasonUpdate.as_view(), name='CallReasonUpdate'),
    path('call_reasons/<int:pk>/delete/', CallReasonDelete.as_view(), name='CallReasonDelete'),
    
    
    path('API/Customers/List/', CustomerAPIList.as_view(), name='CustomerAPIList'),
    path('API/Customers/<int:pk>/', CustomerAPIDetail.as_view(), name='CustomerAPIDetail'),
    ]

HR/urls.py
from .views import *
from django.urls import path

app_name = 'HR'
urlpatterns = [
    path('employees/', EmployeeList.as_view(), name='EmployeeList'),
    path('employees/new/', EmployeeCreate.as_view(), name='EmployeeCreate'),
    path('employees/<int:pk>/edit/', EmployeeUpdate.as_view(), name='EmployeeUpdate'),
    path('employees/<int:pk>/delete/', EmployeeDelete.as_view(), name='EmployeeDelete'),
    path('employees/<int:pk>/view/', EmployeeDetail.as_view(), name='EmployeeDetail'),
    path('employees/<int:pk>/upload/', UploadFile.as_view(), name='UploadFile'),
    path('employees/files/view/<int:pk>/', ViewFile.as_view(), name='ViewFile'),

    ]

ONERP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
#done merge 


urlpatterns = [
    path('admincp/', admin.site.urls),
    path('', include('Website.urls')),
    path('admin/', include('Core.urls')),
    path('auth/', include('Auth.urls')),
    path('products/', include('Products.urls')),
    path('branches/', include('Branches.urls')),
    path('treasuries/', include('Treasuries.urls')),
    path('customers/', include('Customers.urls')),
    path('partners/', include('Partners.urls')),
    path('tasks/', include('Tasks.urls')),
    #path('prices', include('Prices.urls')),
    path('invoices_maged/', include('InvoicesMaged.urls')),
    path('chat/', include('Chat.urls')),    
    path('hr/', include('HR.urls')),
    path('barcode/', include('Barcode.urls')),
    path('invoices/', include('Invoices.urls')),
    path('select2/', include('django_select2.urls')),
    path('reports/', include('Reports.urls')),
    path('calendar/', include('Calendar.urls')),
    path('maintenance/', include('Maintenance.urls')),
    path('projects/', include('Projects.urls')),
    path('technicians/', include('Technicians.urls')),
    path('setup/', include('Setting.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view, name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view, name='password_reset_done'),
    path('reset/<slug:uidb64>/<slug:token>/', auth_views.PasswordResetConfirmView.as_view, name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view, name='password_reset_complete'),
    
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Customers/models.py
from django.db import models
from django.db.models import Count, Sum
from django.db.models import F, FloatField, Sum
from Auth.models import User
from django.db.models.signals import post_save, pre_save
from Technicians.models import Technician


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=128, verbose_name='الاسم')
    deleted = models.BooleanField(default=False, verbose_name='حذف')

    def __str__(self):
        return self.name

    class Meta:
        default_permissions = ()
        permissions = (
            ('add_customer_category', 'إضافة شريحة عملاء'),
            ('edit_customer_category', 'تعديل شريحة عملاء'),
            ('delete_customer_category', 'حذف شريحة عملاء'),
            ('access_customer_category_menu', 'الدخول علي قائمة شرائح العملاء'),
        )


class CustomerType(models.Model):
    name = models.CharField(max_length=128, verbose_name='الاسم')
    deleted = models.BooleanField(default=False, verbose_name='حذف')

    def __str__(self):
        return self.name


class Customer(models.Model):
    color = (
        ('#FF0000', 'احمر'),
        ('#fff400', 'اصفر'),
        ('#00c33e', 'اخضر'),
    )
    name = models.CharField(max_length=128, verbose_name='الاسم')
    phone = models.CharField(max_length=14, null=True, blank=True, verbose_name='الموبايل')
    address = models.TextField(null=True, blank=True, verbose_name='العنوان')
    technician = models.ForeignKey(Technician, on_delete=models.SET_NULL, null=True, blank=True ,verbose_name='الفني الافتراضي')
    payments_status = models.CharField(default="#00c33e",choices=color , max_length=50, verbose_name='حالة الدفعات', null=True, blank=True)
    Products_status = models.CharField(default="#00c33e", choices=color , max_length=50, verbose_name='حالة المنتجات', null=True, blank=True)
    seller_feedback = models.TextField(null=True, blank=True, verbose_name='ملاحظات البائع')
    accountant_notes = models.TextField(null=True, blank=True, verbose_name='ملاحظات المحاسب')
    secret = models.BooleanField(default=False, verbose_name='سري')
    customer_type = models.ForeignKey(CustomerType, on_delete=models.SET_NULL, null=True, blank='True',
                                      verbose_name='نوع العميل')
    facebook_account = models.CharField(max_length=128, verbose_name='حساب الفيس بوك', null=True, blank=True)
    job = models.CharField(max_length=128, null=True, blank=True, verbose_name='مجموعه فرعيه')
    sales_category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True,
                                       verbose_name='شريحة المبيعات', related_name='customers_category')
    purchases_category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True,
                                           verbose_name='شريحة المشتريات', related_name='vendors_category')
    initial_balance = models.FloatField(default=0, verbose_name='الرصيد الافتتاحي')
    allow_negative_balance = models.BooleanField(default=False, verbose_name='السماح بالبيع آجل')
    max_negative_balance = models.FloatField(default=0, verbose_name='الحد الإئتماني')
    added_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='اضيف بواسطة')
    added_at = models.DateTimeField(auto_now_add=True, verbose_name='أضيف بتاريخ')
    main_account = models.ForeignKey('self', on_delete=models.SET_NULL, null=True, blank=True,
                                     verbose_name='الحساب الرئيسي')
    administrator = models.CharField(max_length=128, verbose_name='المسئول', null=True, blank=True)
    purchase_invoices_comments = models.TextField(verbose_name='ملاحظات بفاتوره المشتريات', null=True, blank=True)
    deleted = models.BooleanField(default=False, verbose_name='حذف')
     
    def __str__(self):
        return self.name

    def balance(self):
        invoices = self.invoice_set.filter(deleted=False, saved=True)
        balance = invoices.aggregate(
            total=Sum(F('customer_debit'), output_field=FloatField()) - Sum(F('customer_credit'),
                                                                            output_field=FloatField()),
            debit=Sum('customer_debit'), credit=Sum('customer_credit'))
        if not balance['total']:
            return self.initial_balance
        else:
            return balance['total'] + self.initial_balance

    def total_debit(self):
        invoices = self.invoice_set.filter(deleted=False, saved=True)
        balance = invoices.aggregate(debit=Sum('customer_debit'))
        if self.initial_balance > 0:
            if not balance['debit']:
                return self.initial_balance
            else:
                return balance['debit'] + self.initial_balance
        else:
            if not balance['debit']:
                return 0
            else:
                return balance['debit']

    def total_credit(self):
        invoices = self.invoice_set.filter(deleted=False, saved=True)
        balance = invoices.aggregate(credit=Sum('customer_credit'))
        if self.initial_balance < 0:
            if not balance['credit']:
                return self.initial_balance
            else:
                return balance['credit'] - self.initial_balance
        else:
            if not balance['credit']:
                return 0
            else:
                return balance['credit']

    def is_creditor(self):
        if self.balance():
            if self.balance() < 0:
                return True
            else:
                return False

    def is_debitor(self):
        if self.balance():
            if self.balance() > 0:
                return True
            else:
                return False

    def sales_invoices(self):
        return self.invoice_set.filter(deleted=False, invoice_type=1)

    def quotations(self):
        return self.invoice_set.filter(deleted=False, invoice_type=7)


     
    
    class Meta:
        ordering = ['id']
        default_permissions = ()
        permissions = (
            ('add_customer', 'إضافة عميل/مورد'),
            ('edit_customer', 'تعديل عميل/مورد'),
            ('delete_customer', 'حذف عميل/مورد'),
            ('view_customer', 'عرض بيانات عميل/مورد'),
            ('view_customer_balance', 'عرض رصيد عميل/مورد'),
            ('view_customer_statement', 'كشف حساب عميل/مورد'),
            ('access_customer_menu', 'الدخول علي قائمة العملاء/الموردين'),
        )

       
    
class CustomerNote(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True, blank=True, verbose_name='العميل')
    added_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='الموظف')
    added_at = models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')
    title = models.CharField(max_length=128, verbose_name='عنوان الملاحظات')
    note = models.TextField(verbose_name='محتوي الملاحظة')

    def __str__(self):
        return self.title


class CallReason(models.Model):
    name = models.CharField(verbose_name='سبب الإتصال', max_length=128)
    deleted = models.BooleanField(default=False, verbose_name='حذف')

    def __str__(self):
        return self.name


class CustomerCall(models.Model):
    call_type_choices = (
        (1, 'مكالمة صادرة'),
        (2, 'مكالمة واردة'),
        (3, 'Whatsapp'),
        (4, 'Messenger')
    )
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True, blank=True, verbose_name='العميل')
    added_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='الموظف')
    added_at = models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')
    call_type = models.IntegerField(choices=call_type_choices, verbose_name='نوع المكالمة')
    call_reason = models.ForeignKey(CallReason, on_delete=models.SET_NULL, null=True, verbose_name='سبب المكالمة')
    summary = models.TextField(verbose_name='ملخص المكالمة')

    def __str__(self):
        return self.summary


class CustomerHistory(models.Model):
    history_type_choices = (
        (1, 'إضافة عميل'),
        (2, 'إضافة مكالمة'),
        (3, 'إضافة عرض سعر'),
        (4, 'إضافة فاتورة مبيعات'),
        (5, 'إضافة فاتورة مرتجع مبيعات'),
        (6, 'إضافة فاتورة مشتريات'),
        (7, 'إضافة فاتورة مرتجع مشتريات'),
        (8, 'إضافة ملاحظة'),
        (9, 'إضافة مكالمة'),
        (10, 'تحديد مهام'),
    )
    history_type = models.IntegerField(choices=history_type_choices, verbose_name='نوع العملية')
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True, blank=True, verbose_name='العميل')
    added_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='الموظف')
    added_at = models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')
    call = models.ForeignKey(CustomerCall, on_delete=models.CASCADE, verbose_name='المكالمة', null=True)
    note = models.ForeignKey(CustomerNote, on_delete=models.CASCADE, verbose_name='الملاحظة', null=True)
    invoice_id = models.IntegerField(verbose_name='رقم الفاتورة', null=True)

    def __str__(self):
        return self.get_history_type_display()

    class Meta:
        ordering = ['-added_at']


def save_customer(sender, instance, created, **kwargs):
    if created:
        history = CustomerHistory()
        history.added_by = instance.added_by
        history.added_at = instance.added_at
        history.history_type = 1
        history.customer = instance
        history.save()


post_save.connect(save_customer, sender=Customer)


class Pricing(models.Model):
    name = models.CharField(max_length=128, verbose_name='اسم السعر')

    def __str__(self):
        return self.name

Customers/forms.py
from django import forms


from .models import *


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        exclude = ['deleted']


class CategoryDeleteForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['deleted']
        
        
class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        exclude = ['deleted', 'seller_feedback', 'accountant_notes', 'purchase_invoices_comments']
        widgets = {
            'added_by': forms.HiddenInput(),
            'address': forms.Textarea(attrs={'rows': '2'})
            # 'payments_status': forms.TextInput(attrs={'type': 'color'}),
            # 'Products_status': forms.TextInput(attrs={'type': 'color'}),
        }

class CustomerNotesForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['seller_feedback', 'accountant_notes', 'purchase_invoices_comments']
        exclude = ['deleted']
        widgets = {
            'seller_feedback': forms.Textarea(attrs={'rows': '3'}),
            'accountant_notes': forms.Textarea(attrs={'rows': '3'}),
            'purchase_invoices_comments': forms.Textarea(attrs={'rows': '3'})}




class CustomerEditForm(forms.ModelForm):
    class Meta:
        model = Customer
        exclude = ['deleted', 'added_by']


class CustomerDeleteForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['deleted']




class CallReasonForm(forms.ModelForm):
    class Meta:
        model = CallReason
        exclude = ['deleted']


class CallReasonDeleteForm(forms.ModelForm):
    class Meta:
        model = CallReason
        fields = ['deleted']


class CustomerCallForm(forms.ModelForm):
    class Meta:
        model = CustomerCall
        fields = ['call_type', 'call_reason', 'summary']



class CustomerTypeList(forms.ModelForm):
    class Meta:
        model = CustomerType
        fields = ['name']



class CustomerEditForm(forms.ModelForm):
    class Meta:
        model = CustomerType
        exclude = ['deleted', 'added_by']


class CustomerTypeEditForm(forms.ModelForm):
    class Meta:
        model = CustomerType
        exclude = ['deleted','added_by']
        

class CustomerTypeForm(forms.ModelForm):
    class Meta:
        model = CustomerType
        exclude = ['deleted']
        widgets = {
            'added_by' : forms.HiddenInput(),
        }

class CustomerTypeDeleteForm(forms.ModelForm):
    class Meta:
        model = CustomerType
        fields = ['deleted']

Customers/templates/Customers/customer_calls.html
{% extends 'base.html' %}
{% block body %}
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <div class="card-title">
                    <a href="{% url 'Customers:CustomerDetail' object.id %}">
                        <i class="fa fa-arrow-left"></i> عودة إلي صفحة العميل
                    </a>
                    عرض مكالمات العميل:
                    {{ object.name }}

                </div>
            </div>
            <div class="card-body table-responsive">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <td>#</td>
                        <td>التاريخ</td>
                        <td>نوع المكالمة</td>
                        <td>سبب المكالمة</td>
                        <td>أنشئت بواسطة</td>
                    </tr>
                    </thead>
                    <tbody>
                    {% for x in object.customercall_set.all %}
                        <tr>
                            <td>
                                {{ forloop.counter }}
                            </td>
                            <td>
                                <a href="{% url 'Customers:CallDetail' x.id %}" data-toggle="modal"
                                   data-target="#sub_modal">
                                    {{ x.added_at.date.isoformat }}
                                </a>
                            </td>
                            <td>{{ x.get_call_type_display }}</td>
                            <td>{{ x.call_reason }}</td>
                            <td>{{ x.added_by }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

Customers/templates/Customers/customer_detail.html
{% extends 'base.html' %}
{% block body %}
<div class="col-lg-12">
    <div class="btn-group btn-block">
        <a class="btn btn-app" href="{% url 'Customers:CustomerCalls' object.id %}">
            {% if object.customercall_set.count > 0 %}
            <span class="badge bg-purple">{{ object.customercall_set.count }}</span>
            {% endif %}
            <i class="fas fa-mobile"></i>المكالمات
        </a>
        <a class="btn btn-app" href="{% url 'Customers:CustomerInvoices' object.id %}?type=7">
            {% if object.quotations.count > 0 %}
                <span class="badge bg-purple">{{ object.quotations.count }}</span>
            {% endif %}
            <i class="fas fa-edit"></i> عروض الأسعار
        </a>
        <a class="btn btn-app" href="{% url 'Customers:CustomerInvoices' object.id %}?type=1">
            {% if object.sales_invoices.count > 0 %}
                <span class="badge bg-purple">{{ object.sales_invoices.count }}</span>
            {% endif %}
            <i class="fas fa-list-alt"></i> فواتير المبيعات
        </a>
    </div>
</div>
<div class="col-md-4">
    <a class="btn btn-success btn-block" href="{% url 'Customers:add_call' object.id %}" data-toggle="modal"
       data-target="#sub_modal">
        <i class="fa fa-mobile"></i>
    </a>
    <div class="card">
        <div class="card-header">
            <div class="card-title">
                بيانات العميل / المورد
                <a href="{% url 'Customers:CustomerUpdate' object.id %}" data-toggle="modal"
                   data-target="#sub_modal"
                   class="btn btn-success">
                    <i class="fa fa-edit"></i>
                </a>
            </div>
        </div>
        <div class="card-body">

            <div class="card card-widget widget-user-2">
                <!-- Add the bg color to the header using any of the bg-* classes -->
                <div class="widget-user-header bg-warning">
                  
                  <!-- /.widget-user-image -->
                  <h3 class="widget-user-username">{{ object.name }}</h3>
                  
                  {% if object.job %}
                  <h5 class="widget-user-desc">{{object.job}}</h5>
                  {% endif %}
                      
                
                </div>
                <div class="card-footer p-0">
                  <ul class="nav flex-column">
                    <li class="nav-item">
                      <a href="#" class="nav-link" style="color:black"> 
                          {% if object.address %}
                          العنوان : 
                          <span class=" badge "><h6>{{object.address}}</h6></span>
                          {% endif %}
                      </a>
                    </li>
                    <li class="nav-item">
                      <a href="#" class="nav-link" style="color:black">
                        
                        {% if object.phone %}
                        رقم الموبيل :
                        <span class="badge "><h6>{{object.phone}}</h6></span>
                        {% endif %}
                              
                      </a>
                    </li>
                    {% if object.technician %}
                    <li class="nav-item">
                      <a href="#" class="nav-link b" style="color:black">
                          الفني:
                           <span class="badge"><h6>{{object.technician}}</h6></span>
                      </a>
                    </li>
                    {% endif %}

                    {% if object.customer_type %}
                    <li class="nav-item">
                      <a href="#" class="nav-link b" style="color:black">
                          نوع العميل:
                           <span class="badge"><h6>{{object.customer_type}}</h6></span>
                      </a>
                    </li>
                    {% endif %}

                    {% if object.payments_status%}
                    <li class="nav-item">
                      <a href="#" class="nav-link b" style="color:black">
                          حالة الدفعات :
                           <span ><input type="color" value="{{object.payments_status}}" readonly></span>
                      </a>
                    </li>
                    {% endif %}

                    {% if object.Products_status%}
                    <li class="nav-item">
                      <a href="#" class="nav-link b" style="color:black"  >
                          حالة المنتجات :
                           <span ><input type="color" value="{{object.Products_status}}" readonly></span>
                      </a>
                    </li>
                    {% endif %}

                  </ul>
                </div>
              </div>

            <h5>وسائل التواصل</h5>
            
            {% if object.phone %}
                <a href="tel:{{ object.phone }}" class="btn btn-info">
                    <i class="fa fa-mobile"></i>
                </a>
                <a href="https://wa.me/2{{ object.phone }}" class="btn btn-success" target="_blank">
                    <i class="fab fa-whatsapp"></i>
                </a>
            {% endif %}
            {% if object.name %}
                <a href="https://m.me/{{ object.facebook_account }}" class="btn btn-primary" target="_blank">
                    <i class="fab fa-facebook-messenger"></i>
                </a>
            {% endif %}
        </div>
    </div>
    <div class="card">
        <div class="card-header">
            <div class="card-title">
                الخط الزمني
            </div>
        </div>
        <div class="card-body">

            <!-- The time line -->
            <div class="timeline">
                <!-- timeline time label -->
                {% regroup object.customerhistory_set.all by added_at.date.isoformat as object_list %}
                {% for x in object_list %}
                    <div class="time-label">
                        <span class="bg-red">{{ x.grouper }}</span>
                    </div>
                    <!-- /.timeline-label -->
                    {% for y in x.list %}
                        <!-- timeline item -->
                        {% if y.history_type == 1 %}
                            <div>
                                <i class="fas fa-user-plus bg-green"></i>
                                <div class="timeline-item">
                                    <span class="time"><i class="fas fa-clock"></i> {{ y.added_at.time }}</span>
                                    <h3 class="timeline-header no-border">

                                        تم إضافة العميل
                                        <a href="#">{{ y.customer.name }}</a>
                                        بواسطة
                                        <a href="#">{{ y.added_by }}</a>
                                    </h3>
                                </div>
                            </div>
                        {% elif y.history_type == 2 %}
                            <div>
                                <i class="fas fa-phone bg-warning"></i>
                                <div class="timeline-item">
                                    <span class="time"><i class="fas fa-clock"></i> {{ y.added_at.time }}</span>
                                    <h3 class="timeline-header no-border">
                                        تم
                                        <a href="{% url 'Customers:CallDetail' y.call.id %}" data-target="#sub_modal" data-toggle="modal">
                                            {{ y.get_history_type_display }}

                                        </a>
                                        بواسطة
                                        <a href="#">{{ y.added_by }}</a>
                                    </h3>
                                </div>
                            </div>
                        {% elif y.history_type == 3 %}
                            <div>
                                <i class="fas fa-list-alt bg-info"></i>
                                <div class="timeline-item">
                                    <span class="time"><i class="fas fa-clock"></i> {{ y.added_at.time }}</span>
                                    <h3 class="timeline-header no-border">

                                        تم إضافة
                                        <a href="#">
                                            {{ y.get_history_type_display }}

                                            {{ y.ivnoice_id }}
                                        </a>
                                        بواسطة
                                        <a href="#">{{ y.added_by }}</a>
                                    </h3>
                                </div>
                            </div>

                        {% elif y.history_type == 4 %}
                            <div>
                                <i class="fas fa-list-alt bg-info"></i>
                                <div class="timeline-item">
                                    <span class="time"><i class="fas fa-clock"></i> {{ y.added_at.time }}</span>
                                    <h3 class="timeline-header no-border">

                                        تم إضافة
                                        <a href="#">
                                            {{ y.get_history_type_display }}

                                            {{ y.ivnoice_id }}
                                        </a>
                                        بواسطة
                                        <a href="#">{{ y.added_by }}</a>
                                    </h3>
                                </div>
                            </div>
                        
                            {% elif y.history_type == 5 %}
                            <div>
                                <i class="fas fa-list-alt bg-info"></i>
                                <div class="timeline-item">
                                    <span class="time"><i class="fas fa-clock"></i> {{ y.added_at.time }}</span>
                                    <h3 class="timeline-header no-border">

                                        تم إضافة
                                        <a href="#">
                                            {{ y.get_history_type_display }}

                                            {{ y.note }}
                                        </a>
                                        بواسطة
                                        <a href="#">{{ y.added_by }}</a>
                                    </h3>
                                </div>
                            </div>    

                         

                        {% endif %}

                        
                        <!-- END timeline item -->
                    {% endfor %}
                {% endfor %}
                <!-- END timeline item -->
                <div>
                    <i class="fas fa-clock bg-gray"></i>
                </div>
            </div>

        </div>
    </div>
</div>
{% endblock %}

Customers/templates/Customers/customercall_detail.html
<div class="card">
    <div class="card-header">
        <div class="card-title">بيانات المكالمة</div>
        {% include 'card-tools.html' %}
    </div>
    <div class="card-body">
        <h4>{{ object.customer }} -
            <small><i class="fa fa-user"></i> {{ object.added_by }}</small>
        </h4>
        <i class="fa fa-calendar"></i> {{ object.added_at.date.isoformat }}
        <i class="fa fa-clock"></i> {{ object.added_at.time }}
        <p>{{ object.summary }}</p>
    </div>
</div>