HR/urls.py
from .views import *
from django.urls import path

app_name = 'HR'
urlpatterns = [
    path('employees/', EmployeeList.as_view(), name='EmployeeList'),
    path('employees/new/', EmployeeCreate.as_view(), name='EmployeeCreate'),
    path('employees/<int:pk>/edit/', EmployeeUpdate.as_view(), name='EmployeeUpdate'),
    path('employees/<int:pk>/delete/', EmployeeDelete.as_view(), name='EmployeeDelete'),
    path('employees/<int:pk>/view/', EmployeeDetail.as_view(), name='EmployeeDetail'),
    path('employees/<int:pk>/upload/', UploadFile.as_view(), name='UploadFile'),
    path('employees/files/view/<int:pk>/', ViewFile.as_view(), name='ViewFile'),

    ]

Invoices/urls.py
from django.urls import path

from .views import *

app_name = 'Invoices'
urlpatterns = [
    path('search/', search_invoice, name='search_invoice'),
    path('setting/print/', invoice_setting, name='invoice_setting'),
    path('setting/base/', invoice_base_setting, name='invoice_base_setting'),
    path('expense/', expense_invoice, name='expense_invoice'),
    path('edit/<int:pk>/fast/', edit_fast_invoice, name='edit_fast_invoice'),
    path('income/', income_invoice, name='income_invoice'),
    path('capital/outcome/', capital_minus, name='capital_minus'),
    path('treasury/transfer/add/', treasury_transfer, name='treasury_transfer'),
    path('capital/income/', capital_plus, name='capital_plus'),
    path('customer/outcome/', customer_outcome, name='customer_outcome'),
    path('customer/income/', customer_income, name='customer_income'),
    path('new/<int:type>/', make_invoice, name='make_invoice'),
    path('show/<int:pk>/', show_invoice, name='show_invoice'),
    path('print/<int:pk>/', print_invoice, name='print_invoice'),
    path('last/<int:type>/', get_last_invoice, name='get_last_invoice'),
    path('save/<int:pk>/', save_invoice, name='save_invoice'),
    path('add_customer/<int:pk>/', add_customer_to_invoice, name='add_customer_to_invoice'),
    path('unsave/<int:pk>/', unsave_invoice, name='unsave_invoice'),
    path('delete/<int:pk>/', delete_invoice, name='delete_invoice'),
    path('super_delete/<int:pk>/', super_delete, name='super_delete'),
    path('opened/<int:type>/', show_opened_invoices, name='show_opened_invoices'),
    path('edit/discount/<int:pk>/', edit_invoice_discount, name='edit_invoice_discount'),
    path('edit/customer/<int:pk>/', edit_invoice_customer, name='edit_invoice_customer'),
    path('edit/branch/<int:pk>/', edit_invoice_branch, name='edit_invoice_branch'),
    path('edit/treasury/<int:pk>/', edit_invoice_treasury, name='edit_invoice_treasury'),
    path('edit/date/<int:pk>/', edit_invoice_date, name='edit_invoice_date'),
    path('items/delete/<int:pk>/', delete_invoice_item, name='delete_invoice_item'),
    path('items/edit/price/<int:pk>/', edit_invoice_item_price, name='edit_invoice_item_price'),
    path('items/edit/main_price/<int:pk>/', edit_invoice_item_main_price, name='edit_invoice_item_main_price'),
    path('items/edit/quantity/<int:pk>/', edit_invoice_item_quantity, name='edit_invoice_item_quantity'),
    path('items/edit/discount/<int:pk>/', edit_invoice_item_discount, name='edit_invoice_item_discount'),
    path('<int:invoice_id>/get_unit_price/', get_unit_price, name='get_unit_price'),
    path('spend_categories/', SpendCategoryList.as_view(), name='SpendCategoryList'),
    path('spend_categories/new/', SpendCategoryCreate.as_view(), name='SpendCategoryCreate'),
    path('spend_categories/trash/', SpendCategoryTrashList.as_view(), name='SpendCategoryTrashList'),
    path('spend_categories/<int:pk>/edit/', SpendCategoryUpdate.as_view(), name='SpendCategoryUpdate'),
    path('spend_categories/<int:pk>/delete/', SpendCategoryDelete.as_view(), name='SpendCategoryDelete'),

    path('<int:invoice_id>/get_unit_all_price/', get_unit_all_price, name='get_unit_all_price'),
    path('get_product_units/', get_product_units, name='get_product_units'),
    path('add_product/<int:pk>/', add_product_to_invoice, name='add_product_to_invoice'),
    path('add_product2/<int:pk>/', add_product_to_invoice2, name='add_product_to_invoice2'),
    path('items/edit/main_warehouse/<int:pk>/', edit_invoice_item_main_warehouse, name='edit_invoice_item_main_warehouse'),
    path('items/edit/sub_warehouse/<int:pk>/', edit_invoice_item_sub_warehouse, name='edit_invoice_item_sub_warehouse'),
    path('pay/<int:pk>/', pay_invoice, name='pay_invoice'),
    path('out/<int:pk>/', out_invoice, name='out_invoice'),
    path('edit/warehouse/<int:pk>/', edit_invoice_warehouse, name='edit_invoice_warehouse'),
    path('<int:invoice_id>/get_form_main_warehouse/', get_form_main_warehouse, name='get_form_main_warehouse'),
    path('<int:invoice_id>/get_form_sub_warehouse/', get_form_sub_warehouse, name='get_form_sub_warehouse'),
    path('<int:invoice_id>/get_form_all_warehouse/', get_form_all_warehouse, name='get_form_all_warehouse'),
    path('get_product_sell_comment/', get_product_sell_comment, name='get_product_sell_comment'),
    path('get_customer_sell_comment/', get_customer_sell_comment, name='get_customer_sell_comment'),
    path('edit/invoice_main_warehouse/<int:pk>/', edit_invoice_main_warehouse, name='edit_invoice_main_warehouse'),
    path('edit/invoice_sub_warehouse/<int:pk>/', edit_invoice_sub_warehouse, name='edit_invoice_sub_warehouse'),
    path('display_all_prods/', display_all_prods, name='display_all_prods'),

]

InvoicesMaged/urls.py
from django.urls import path

from .views import *

app_name = 'InvoicesMaged'
urlpatterns = [
    path('search/', search_invoice, name='search_invoice'),
    path('setting/print/', invoice_setting, name='invoice_setting'),
    path('setting/base/', invoice_base_setting, name='invoice_base_setting'),
    path('expense/', expense_invoice, name='expense_invoice'),
    path('edit/<int:pk>/fast/', edit_fast_invoice, name='edit_fast_invoice'),
    path('income/', income_invoice, name='income_invoice'),
    path('capital/outcome/', capital_minus, name='capital_minus'),
    path('treasury/transfer/add/', treasury_transfer, name='treasury_transfer'),
    path('capital/income/', capital_plus, name='capital_plus'),
    # path('customer/outcome/', customer_outcome, name='customer_outcome'),
    # path('customer/income/', customer_income, name='customer_income'),
    path('new/<int:type>/', make_invoice, name='make_invoice'),
    path('show/<int:pk>/', show_invoice, name='show_invoice'),
    path('print/<int:pk>/', print_invoice, name='print_invoice'),
    path('last/<int:type>/', get_last_invoice, name='get_last_invoice'),
    path('save/<int:pk>/', save_invoice, name='save_invoice'),
    path('add_customer/<int:pk>/', add_customer_to_invoice, name='add_customer_to_invoice'),
    path('unsave/<int:pk>/', unsave_invoice, name='unsave_invoice'),
    path('delete/<int:pk>/', delete_invoice, name='delete_invoice'),
    path('super_delete/<int:pk>/', super_delete, name='super_delete'),
    path('opened/<int:type>/', show_opened_invoices, name='show_opened_invoices'),
    path('edit/discount/<int:pk>/', edit_invoice_discount, name='edit_invoice_discount'),
    path('edit/customer/<int:pk>/', edit_invoice_customer, name='edit_invoice_customer'),
    path('edit/branch/<int:pk>/', edit_invoice_branch, name='edit_invoice_branch'),
    path('edit/treasury/<int:pk>/', edit_invoice_treasury, name='edit_invoice_treasury'),
    path('edit/date/<int:pk>/', edit_invoice_date, name='edit_invoice_date'),
    path('items/delete/<int:pk>/', delete_invoice_item, name='delete_invoice_item'),
    path('items/edit/price/<int:pk>/', edit_invoice_item_price, name='edit_invoice_item_price'),
    path('items/edit/quantity/<int:pk>/', edit_invoice_item_quantity, name='edit_invoice_item_quantity'),
    path('items/edit/discount/<int:pk>/', edit_invoice_item_discount, name='edit_invoice_item_discount'),
    path('<int:invoice_id>/get_unit_price/', get_unit_price, name='get_unit_price'),
    # path('spend_categories/', SpendCategoryList.as_view(), name='SpendCategoryList'),
    # path('spend_categories/new/', SpendCategoryCreate.as_view(), name='SpendCategoryCreate'),
    # path('spend_categories/trash/', SpendCategoryTrashList.as_view(), name='SpendCategoryTrashList'),
    # path('spend_categories/<int:pk>/edit/', SpendCategoryUpdate.as_view(), name='SpendCategoryUpdate'),
    # path('spend_categories/<int:pk>/delete/', SpendCategoryDelete.as_view(), name='SpendCategoryDelete'),

    ##############################################################

    path('add_product/<int:pk>/', add_product_to_invoice, name='add_product_to_invoice'),
    path('<int:invoice_id>/get_unit_all_price/', get_unit_all_price, name='get_unit_all_price'),
    path('get_product_units/', get_product_units, name='get_product_units'),
    path('items/edit/main_warehouse/<int:pk>/', edit_invoice_item_main_warehouse, name='edit_invoice_item_main_warehouse'),
    path('items/edit/sub_warehouse/<int:pk>/', edit_invoice_item_sub_warehouse, name='edit_invoice_item_sub_warehouse'),
    path('pay/<int:pk>/', pay_invoice, name='pay_invoice'),
    path('out/<int:pk>/', out_invoice, name='out_invoice'),

]

ONERP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
#done merge 


urlpatterns = [
    path('admincp/', admin.site.urls),
    path('', include('Website.urls')),
    path('admin/', include('Core.urls')),
    path('auth/', include('Auth.urls')),
    path('products/', include('Products.urls')),
    path('branches/', include('Branches.urls')),
    path('treasuries/', include('Treasuries.urls')),
    path('customers/', include('Customers.urls')),
    path('partners/', include('Partners.urls')),
    path('tasks/', include('Tasks.urls')),
    #path('prices', include('Prices.urls')),
    path('invoices_maged/', include('InvoicesMaged.urls')),
    path('chat/', include('Chat.urls')),    
    path('hr/', include('HR.urls')),
    path('barcode/', include('Barcode.urls')),
    path('invoices/', include('Invoices.urls')),
    path('select2/', include('django_select2.urls')),
    path('reports/', include('Reports.urls')),
    path('calendar/', include('Calendar.urls')),
    path('maintenance/', include('Maintenance.urls')),
    path('projects/', include('Projects.urls')),
    path('technicians/', include('Technicians.urls')),
    path('setup/', include('Setting.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view, name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view, name='password_reset_done'),
    path('reset/<slug:uidb64>/<slug:token>/', auth_views.PasswordResetConfirmView.as_view, name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view, name='password_reset_complete'),
    
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Products/urls.py
from .views import *
from django.urls import path

app_name = 'Products'
urlpatterns = [
    path('main_categories/', MainCategoryList.as_view(), name='MainCategoryList'),
    path('main_categories/new/', MainCategoryCreate.as_view(), name='MainCategoryCreate'),
    path('main_categories/trash/', MainCategoryTrashList.as_view(), name='MainCategoryTrashList'),
    path('main_categories/<int:pk>/edit/', MainCategoryUpdate.as_view(), name='MainCategoryUpdate'),
    path('main_categories/<int:pk>/delete/', MainCategoryDelete.as_view(), name='MainCategoryDelete'),
    
    path('sub_categories/', SubCategoryList.as_view(), name='SubCategoryList'),
    path('sub_categories/new/', SubCategoryCreate.as_view(), name='SubCategoryCreate'),
    path('sub_categories/trash/', SubCategoryTrashList.as_view(), name='SubCategoryTrashList'),
    path('sub_categories/<int:pk>/edit/', SubCategoryUpdate.as_view(), name='SubCategoryUpdate'),
    path('sub_categories/<int:pk>/delete/', SubCategoryDelete.as_view(), name='SubCategoryDelete'),

    path('manufactures/', ManufactureList.as_view(), name='ManufactureList'),
    path('manufactures/new/', ManufactureCreate.as_view(), name='ManufactureCreate'),
    path('manufactures/trash/', ManufactureTrashList.as_view(), name='ManufactureTrashList'),
    path('manufactures/<int:pk>/edit/', ManufactureUpdate.as_view(), name='ManufactureUpdate'),
    path('manufactures/<int:pk>/delete/', ManufactureDelete.as_view(), name='ManufactureDelete'),

    path('brands/', BrandList.as_view(), name='BrandList'),
    path('brands/new/', BrandCreate.as_view(), name='BrandCreate'),
    path('brands/trash/', BrandTrashList.as_view(), name='BrandTrashList'),
    path('brands/<int:pk>/edit/', BrandUpdate.as_view(), name='BrandUpdate'),
    path('brands/<int:pk>/delete/', BrandDelete.as_view(), name='BrandDelete'),

    path('units/', UnitList.as_view(), name='UnitList'),
    path('units/new/', UnitCreate.as_view(), name='UnitCreate'),
    path('units/trash/', UnitTrashList.as_view(), name='UnitTrashList'),
    path('units/<int:pk>/edit/', UnitUpdate.as_view(), name='UnitUpdate'),
    path('units/<int:pk>/delete/', UnitDelete.as_view(), name='UnitDelete'),

    path('products/', ProductList.as_view(), name='ProductList'),
    path('products/new/', ProductCreate.as_view(), name='ProductCreate'),
    path('products/add/', product_create, name='product_create'),
    path('products/trash/', ProductTrashList.as_view(), name='ProductTrashList'),
    path('products/<int:pk>/edit/', ProductUpdate.as_view(), name='ProductUpdate'),
    path('products/<int:pk>/delete/', ProductDelete.as_view(), name='ProductDelete'),
    path('products/<int:pk>/show/', ProductCard.as_view(), name='ProductCard'),
    path('products/<int:pk>/add_content/', GroupedProductCreate.as_view(), name='GroupedProductCreate'),
    path('products/<int:pk>/note_update/', ProductNoteUpdate.as_view(), name='ProductNoteUpdate'),

    path('grouped_product/<int:pk>/<int:ppk>/edit/', GroupedProductUpdate.as_view(), name='GroupedProductUpdate'),
    path('grouped_product/<int:pk>/<int:ppk>/delete/', GroupedProductDelete.as_view(), name='GroupedProductDelete'),

    #########################################

    path('prices/<int:pk>/add_content/', PricesProductCreate.as_view(), name='PricesProductCreate'),
    path('prices_product/<int:pk>/<int:ppk>/edit/', PricesProductUpdate.as_view(), name='PricesProductUpdate'),
    path('prices_product/<int:pk>/<int:ppk>/delete/', PricesProductDelete.as_view(), name='PricesProductDelete'),
    path('prices_product/<int:pk>/stop/', PricesProductStop.as_view(), name='PricesProductStop'),
    path('prices_product/<int:pk>/active/', PricesProductActive.as_view(), name='PricesProductActive'),
    path('prices_product/editAll/', PricesProductEditAll, name='PricesProductEditAll'),
    path('products/<int:pk>/editPrice/', ProductPriceUpdate.as_view(), name='ProductPriceUpdate'),

    path('main_prices/', MainPricesList.as_view(), name='MainPricesList'),
    path('main_prices/new/', MainPricesListCreate.as_view(), name='MainPricesListCreate'),
    path('main_prices/trash/', MainPricesTrashList.as_view(), name='MainPricesTrashList'),
    path('main_prices/<int:pk>/edit/', MainPricesListUpdate.as_view(), name='MainPricesListUpdate'),
    path('main_prices/<int:pk>/delete/', MainPricesListDelete.as_view(), name='MainPricesListDelete'),
    path('main_prices/<int:pk>/show/', PricesListCard.as_view(), name='PricesListCard'),
    path('prices_product_list/editAll/', PricesProductListEditAll, name='PricesProductListEditAll'),

    path('product_units/<int:pk>/add_unit/', ProductUnitCreate.as_view(), name='ProductUnitCreate'),
    path('product_units/<int:pk>/edit/', ProductUnitUpdate.as_view(), name='ProductUnitUpdate'),
    path('product_units/<int:pk>/delete/', ProductUnitDelete.as_view(), name='ProductUnitDelete'),


    path('customerprices/<int:pk>/<int:ppk>/edit/', CustomerPricesUpdate.as_view(), name='CustomerPricesUpdate'),
    path('customerprices/<int:pk>/<int:ppk>/delete/', CustomerPricesDelete.as_view(), name='CustomerPricesDelete'),

]

InvoicesMaged/templates/Invoices/OneByOne/opened_invoices_m.html
{% extends 'base.html' %}
{% block body %}
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header p-0 border-bottom-0">

                <ul class="nav nav-tabs" role="tablist">
                    {% for x in opened_invoices %}
                        <li class="nav-item">
                            <a href="{% url 'InvoicesMaged:show_invoice' x.id %}"
                               class="nav-link btn btn-{% if x.id == invoice.id %}primary{% else %}info{% endif %}">
                                {{ x.id }}
                            </a>
                        </li>
                    {% endfor %}
                    <li class="nav-item">
                        <a href="{% url 'InvoicesMaged:make_invoice' type %}"
                           class="nav-link btn btn-success">
                            <i class="fa fa-plus-circle"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

InvoicesMaged/templates/Invoices/OneByOne/pos_invoice_m.html
{% extends 'base.html' %}
{% block container_class %}-fluid{% endblock %}
{% block body %}
    <div class="col-lg-4 col-md-4">
        <div class="card">
            <div class="card-header bg-primary text-light">
                <div class="card-title">{{ invoice }}</div>
            </div>
            <div class="card-body table-responsive">
                <table class="table table-hover">
                    <thead>
                    <td>
                        المنتج
                        {% if invoice.invoice_can_edit %}
                            <a href="{% url 'Products:ProductCreate' %}" data-toggle="modal"
                               data-target="#sub_modal"
                               class="btn-sm btn-success">
                                <i class="fa fa-plus-circle"></i>
                            </a>
                        {% endif %}
                    </td>
                    <td>الكمية</td>
                    <td>سعر</td>
                    <td>إجمالي</td>
                    </thead>
                    <tbody>
                    {% for item in invoice.invoiceitem_set.all %}
                        <tr>
                            <td>
                                {{ item.item }}
                            </td>
                            <td>
                                {{ item.quantity|floatformat }}
                                {% if invoice.invoice_can_edit %}
                                    <a href="{% url 'InvoicesMaged:edit_invoice_item_quantity' item.id %}"
                                       class="btn-sm btn-warning dont-print"
                                       data-toggle="modal" data-target="#action_modal">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                {% endif %}
                            </td>
                            <td>
                                {{ item.unit_price|floatformat }}
{#                                {% if perms.Invoices.edit_item_unit_price %}#}
                                    {% if invoice.invoice_can_edit %}
                                        <a href="{% url 'InvoicesMaged:edit_invoice_item_price' item.id %}"
                                           class="btn-sm btn-warning dont-print"
                                           data-toggle="modal" data-target="#action_modal">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                    {% endif %}
{#                                {% endif %}#}
                            </td>
                            <td>
                                {{ item.total_price|floatformat }}
                            </td>
                        </tr>
                    {% endfor %}
                    <tr>
                        <td>إجمالي</td>
                        <td></td>
                        <td></td>
                        <td>{{ invoice.total|floatformat }}</td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="card" style="bottom: 0;">
            <div class="card-body">
                <div class="row">
                    <input type="number" name="quantity" id="quantity">
                    <div class="col-lg-8">
                        <div class="row">
                            <div class="col-3">
                                <button class="btn btn-block" onclick="keypress(1)">1</button>
                            </div>
                            <div class="col-3">
                                <button class="btn btn-block" onclick="keypress(2)">2</button>
                            </div>
                            <div class="col-3">
                                <button class="btn btn-block" onclick="keypress(3)">3</button>
                            </div>
                            <div class="col-3">
                                <button class="btn btn-block">كمية</button>
                            </div>
                            <div class="col-3">
                                <button class="btn btn-block" onclick="keypress(4)">4</button>
                            </div>
                            <div class="col-3">
                                <button class="btn btn-block" onclick="keypress(5)">5</button>
                            </div>
                            <div class="col-3">
                                <button class="btn btn-block" onclick="keypress(6)">6</button>
                            </div>
                            <div class="col-3">
                                <button class="btn btn-block" onclick="keypress()">خصم</button>
                            </div>
                            <div class="col-3">
                                <button class="btn btn-block" onclick="keypress(7)">7</button>
                            </div>
                            <div class="col-3">
                                <button class="btn btn-block" onclick="keypress(8)">8</button>
                            </div>
                            <div class="col-3">
                                <button class="btn btn-block" onclick="keypress(9)">9</button>
                            </div>
                            <div class="col-3">
                                <button class="btn btn-block">سعر</button>
                            </div>
                            <div class="col-3">
                                <button class="btn btn-block" onclick="increase()">+</button>
                            </div>
                            <div class="col-3">
                                <button class="btn btn-block" onclick="keypress(0)">0</button>
                            </div>
                            <div class="col-3">
                                <button class="btn btn-block" onclick="decrease()">-</button>
                            </div>
                            <div class="col-3">
                                <button class="btn btn-block" onclick="backspace()"><i class="fa fa-backspace"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <a class="btn btn-primary btn-block" href="{% url 'InvoicesMaged:edit_invoice_customer' invoice.id %}"
                           data-toggle="modal" data-target="#sub_modal"><i class="fa fa-user-circle"></i>
                            {% if invoice.customer %} {{ invoice.customer }}{% else %}عميل{% endif %}</a>
                        <a class="btn btn-success btn-block" href="{% url 'InvoicesMaged:save_invoice' invoice.id %}"
                           data-toggle="modal" data-target="#sub_modal"><i class="fa fa-dollar-sign"></i> دفع </a>
                        <a class="btn btn-danger btn-block" href="{% url 'InvoicesMaged:delete_invoice' invoice.id %}"
                           data-toggle="modal" data-target="#sub_modal"><i class="fa fa-trash"></i> حذف </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <form>
                    <input type="text" placeholder="#" name="id" id="#product_id">
                    <input type="text" placeholder="#" name="item_id" id="#invoice_item_id">
                    <input type="text" placeholder="اسم المنتج" name="product_name" id="#product_name">
                    <input type="text" placeholder="كمية" name="quantity" id="item_quantity">
                    <input type="text" placeholder="سعر" name="total_price" id="#unit_price">
                    <input type="text" placeholder="اجمالي" name="total" id="#total">
                    <input type="text" placeholder="خصم" name="discount" id="#discount">
                    <input type="text" placeholder="بعد الخصم" name="after_discount" id="#after_discount">
                    <input type="text" placeholder="اخر سعر بيع" name="last_price" id="#last_price">
                    <input type="text" placeholder="الكمية الموجودة في الفرع" name="stock_remaining"
                           id="#stock_remaining">


                </form>
            </div>
        </div>
    </div>
    <div class="col-lg-8 col-md-8">
        <div class="card text-center">
            <div class="card-header bg-primary">
                <div class="row">
                    <div class="col-lg-8 col-md-8">
                        <ul class="nav nav-tabs card-header-tabs">
                            {% for x in opened_invoices %}
                                <li class="nav-item">
                                    <a href="{% url 'InvoicesMaged:show_invoice' x.id %}"
                                       class="nav-link {% if invoice.id == x.id %}active{% endif %}">
                                        {% if invoice.id == x.id %}
                                            <i class="badge badge-dark">{{ x.id }}</i> {{ invoice.date.time }}
                                        {% else %}
                                            {{ x.id }}
                                        {% endif %}
                                    </a>
                                </li>
                            {% endfor %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'InvoicesMaged:make_invoice' invoice.invoice_type %}">
                                    <i class="fa fa-plus-circle"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-lg-3 col-md-3">
                        <form class="">
                            <div class="row">
                                <div class="col-lg-10 col-md-10 col-sm-10 col-10">
                                    <input type="text" placeholder="بحث ..">
                                </div>
                                <div class="col-lg-2 col-md-2 col-sm-2 col-2">
                                    <button type="submit" class="btn-sm"><i class="fa fa-search"></i></button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="card-body" id="product_list">
                <div class="row">
                    <div class="col-lg-4 col-md-4 col-sm-3 col-6">

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script>
        /* KeyPad */
        function keypress(num) {
            var old_pin = $('#quantity').val();
            var new_pin = old_pin + num;
            $('#quantity').val(new_pin);
        }

        function backspace() {
            $('#quantity').val(function (index, value) {
                    return value.substr(0, value.length - 1);
                }
            )
        }

        function increase() {
            $('#quantity').val(function (i, oldval) {
                return ++oldval;
            });
        }

        function decrease() {
            $('#quantity').val(function (i, oldval) {
                return --oldval;
            });
        }
    </script>
{% endblock %}

InvoicesMaged/templates/Invoices/OneByOne/product_units_filter.html
    <option value="">---------</option>
    <option value="{{ product.main_unit.id }}">{{ product.main_unit.name }}</option>
    {%  for item in produc_units %}
        <option value="{{ item.unit_name.id }}">{{ item.unit_name.name }}</option>
    {% endfor %}