Barcode/urls.py
from .views import *
from django.urls import path

app_name = 'Barcode'
urlpatterns = [
        path('generator/single/<int:barcode>/', barcode_generator, name='single_generator'),
        path('view/', view_barcode, name='view_barcode'),
        path('print/', print_barcode, name='print_barcode'),
        path('setting/', barcode_setting, name='barcode_setting'),
        path('print/invoice/<int:pk>/', print_barcode_for_invoice, name='print_barcode_for_invoice'),
        ]

HR/urls.py
from .views import *
from django.urls import path

app_name = 'HR'
urlpatterns = [
    path('employees/', EmployeeList.as_view(), name='EmployeeList'),
    path('employees/new/', EmployeeCreate.as_view(), name='EmployeeCreate'),
    path('employees/<int:pk>/edit/', EmployeeUpdate.as_view(), name='EmployeeUpdate'),
    path('employees/<int:pk>/delete/', EmployeeDelete.as_view(), name='EmployeeDelete'),
    path('employees/<int:pk>/view/', EmployeeDetail.as_view(), name='EmployeeDetail'),
    path('employees/<int:pk>/upload/', UploadFile.as_view(), name='UploadFile'),
    path('employees/files/view/<int:pk>/', ViewFile.as_view(), name='ViewFile'),

    ]

Maintenance/urls.py
from .views import *
from django.urls import path

app_name = 'Maintenance'
urlpatterns = [
    path('tickets/', TicketList.as_view(), name='TicketList'),
    path('tickets/new/', TicketCreate.as_view(), name='TicketCreate'),
    path('tickets/trash/', TicketTrashList.as_view(), name='TicketTrashList'),
    path('tickets/setting/', maintenance_print_setting, name='maintenance_print_setting'),
    path('tickets/<int:pk>/', TicketDetail.as_view(), name='TicketDetail'),
    path('tickets/<int:pk>/reply/', TicketReplyCreate.as_view(), name='TicketReplyCreate'),
    path('tickets/<int:pk>/done/', TicketDone.as_view(), name='TicketDone'),
    path('tickets/<int:pk>/reject/', RejectTicket.as_view(), name='RejectTicket'),
    path('tickets/<int:pk>/edit/', TicketUpdate.as_view(), name='TicketUpdate'),
    path('tickets/<int:pk>/delete/', TicketDelete.as_view(), name='TicketDelete'),
    path('tickets/<int:pk>/transfer/', TransferTo.as_view(), name='TransferTo'),
    path('tickets/<int:pk>/outsource/send/', OutsourceTransfer.as_view(), name='OutsourceTransfer'),
    path('tickets/<int:pk>/outsource/receive/', OutsourceReceived.as_view(), name='OutsourceReceived'),
    path('tickets/<int:pk>/diagnosis/', Diagnosis.as_view(), name='Diagnosis'),
    path('tickets/<int:pk>/cost/rating/', CostRating.as_view(), name='CostRating'),
    path('tickets/<int:pk>/customer/reply/', CustomerReply.as_view(), name='CustomerReply'),
    path('tickets/<int:pk>/customer/receive/', CustomerReceived.as_view(), name='CustomerReceived'),
    path('tickets/<int:pk>/print/receipt/', print_receipt, name='print_receipt'),
    ]

ONERP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
#done merge 


urlpatterns = [
    path('admincp/', admin.site.urls),
    path('', include('Website.urls')),
    path('admin/', include('Core.urls')),
    path('auth/', include('Auth.urls')),
    path('products/', include('Products.urls')),
    path('branches/', include('Branches.urls')),
    path('treasuries/', include('Treasuries.urls')),
    path('customers/', include('Customers.urls')),
    path('partners/', include('Partners.urls')),
    path('tasks/', include('Tasks.urls')),
    #path('prices', include('Prices.urls')),
    path('invoices_maged/', include('InvoicesMaged.urls')),
    path('chat/', include('Chat.urls')),    
    path('hr/', include('HR.urls')),
    path('barcode/', include('Barcode.urls')),
    path('invoices/', include('Invoices.urls')),
    path('select2/', include('django_select2.urls')),
    path('reports/', include('Reports.urls')),
    path('calendar/', include('Calendar.urls')),
    path('maintenance/', include('Maintenance.urls')),
    path('projects/', include('Projects.urls')),
    path('technicians/', include('Technicians.urls')),
    path('setup/', include('Setting.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view, name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view, name='password_reset_done'),
    path('reset/<slug:uidb64>/<slug:token>/', auth_views.PasswordResetConfirmView.as_view, name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view, name='password_reset_complete'),
    
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Maintenance/models.py
from django.db import models
from django.utils.timezone import now

from Auth.models import User
from Customers.models import Customer
from Products.models import Product


# Create your models here.
class Ticket(models.Model):
    status_choices = (
        (1, 'قيد التشخيص'),
        (2, 'قيد التقييم'),
        (3, 'في انتظار رد العميل'),
        (4, 'العميل يرفض التكلفة'),
        (5, 'العميل يرفض فترة الإصلاح'),
        (6, 'قيد الإصلاح'),
        (7, 'تمت الصيانة'),
        (8, 'لا يمكن الإصلاح')
    )
    outsource_status_choices = (
        (1, 'صيانة داخلية'),
        (2, 'تم تحويلها لصيانة خارجية'),
        (3, 'تم استلامها من الصيانة الخارجية'),
    )
    customer_reply_choices = (
        (1, "لم يتم الرد"),
        (2, 'العميل موافق علي التكلفة'),
        (3, 'العميل يرفض التكلفة')
    )
    maintenance_type_choices = (
        (1, 'صيانة'),
        (2, 'ضمان')
    )
    date = models.DateTimeField(default=now, verbose_name='تاريخ فتح التذكرة')
    customer = models.ForeignKey(Customer, verbose_name='العميل', on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, verbose_name='المنتج', on_delete=models.SET_NULL, null=True)
    employee = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='موجه إلي')
    sn = models.CharField(max_length=128, verbose_name='السيريال', null=True, blank=True)
    maintenance_type = models.PositiveSmallIntegerField(default=1, verbose_name='نوع الصيانة',
                                                        choices=maintenance_type_choices)
    problem = models.TextField(verbose_name='المشكلة')
    notes = models.TextField(verbose_name='ملاحظات', null=True, blank=True)
    diagnosis = models.TextField(verbose_name='التشخيص')
    cost = models.PositiveIntegerField(verbose_name='التكلفة', null=True, blank=True, default=0)
    status = models.PositiveSmallIntegerField(default=1, choices=status_choices, verbose_name='حالة التذكرة')
    outsource_status = models.PositiveSmallIntegerField(default=1, choices=outsource_status_choices)
    outsource = models.CharField(max_length=128, verbose_name='حولت إلي', null=True, blank=True)
    shipping_company = models.CharField(max_length=128, verbose_name='شركة الشحن', null=True, blank=True)
    shipping_id = models.CharField(max_length=128, verbose_name='بوليصة الشحن', null=True, blank=True)
    shipping_company2 = models.CharField(max_length=128, verbose_name='شركة الشحن', null=True, blank=True)
    shipping_id2 = models.CharField(max_length=128, verbose_name='بوليصة الشحن', null=True, blank=True)
    customer_received = models.BooleanField(default=False, verbose_name='استلام')
    customer_reply = models.PositiveSmallIntegerField(default=0, verbose_name='رد العميل',
                                                      choices=customer_reply_choices)
    reject_reason = models.TextField(null=True, blank=True, verbose_name='سبب رفض الصيانة')
    done = models.BooleanField(default=False, verbose_name='تمت الصيانة؟')
    deleted = models.BooleanField(default=False, verbose_name='حذف')

    def __str__(self):
        return str(self.id)

    class Meta:
        ordering = ['-id']
        default_permissions = ()


class TicketReply(models.Model):
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE, verbose_name='رقم التذكرة')
    date = models.DateTimeField(default=now, verbose_name='التوقيت')
    employee = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, verbose_name='الموظف')
    reply = models.TextField(verbose_name='الرد')
    notify_customer = models.BooleanField(default=False, verbose_name='تنبيه العميل؟')

    def __str__(self):
        return self.reply

    class Meta:
        ordering = ['-id']
        default_permissions = ()


class PrintSetting(models.Model):
    location_choices = (
        (1, 'يمين الفاتورة'),
        (2, 'يسار الفاتورة'),
    )
    footer1_location_choices = (
        (1, 'أعلي الإيصال'),
        (2, 'أسفل الإيصال')
    )
    size_choices = (
        (1, 'A4/A5'),
        (2, 'طابعة ريسيت 8سم')
    )
    size = models.IntegerField(choices=size_choices, default=1, verbose_name='حجم الطباعة')
    name = models.CharField(max_length=128, null=True, blank=True, verbose_name='اسم الشركة')
    logo = models.ImageField(null=True, blank=True, verbose_name='اللوجو')
    logo_width = models.FloatField(default=100, verbose_name='نسبة عرض اللوجو في الإيصال')
    logo_location = models.IntegerField(choices=location_choices, default=1, verbose_name='موقع اللوجو')
    text_size = models.FloatField(default=12, verbose_name='حجم الخط في الوصل')
    sales_invoice_title = models.CharField(default='إيصال صيانة', max_length=128,
                                           verbose_name="عنوان الإيصال")
    footer1 = models.TextField(null=True, blank=True, verbose_name='النص 1')
    footer2 = models.TextField(null=True, blank=True, verbose_name='النص 2')
    footer1_location = models.IntegerField(choices=footer1_location_choices, default=2, verbose_name='موضع النص 1')

    def __str__(self):
        return str(self.id)

    class Meta:
        default_permissions = ()
        permissions = (
            ('edit_maintenance_receipt_setting', 'تعديل إعدادات طباعة إيصالات الصيانة'),
        )

Maintenance/forms.py
from .models import *
from django import forms


class TicketForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = [
            'customer',
            'product',
            'sn',
            'maintenance_type',
            'problem',
            'notes',
        ]


class TicketDiagnosisForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = [
            'diagnosis',
            'cost',
        ]


class TicketDeleteForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = [
            'deleted',
        ]


class TicketTransferForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = [
            'employee',
        ]


class OutSourceTransferForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = [
            'outsource',
            'shipping_company',
            'shipping_id',
        ]


class CostRatingForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = [
            'cost',
        ]


class DiagnosisForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = [
            'diagnosis',
        ]


class CustomerReplyForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = [
            'customer_reply',
        ]


class TicketDoneForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = [
            'done',
        ]


class OutsourceReceiveForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = [
            'shipping_company2',
            'shipping_id2',
        ]


class OutsourceTransferForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = [
            'outsource',
            'shipping_company',
            'shipping_id',
        ]


class TickerRejectForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = [
            'reject_reason',
        ]


class CustomerReceivedForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = [
            'customer_received',
        ]


class TickerReplyForm(forms.ModelForm):
    class Meta:
        model = TicketReply
        fields = [
            'reply',
            'notify_customer',
        ]


class MaintenancePrintSettingForm(forms.ModelForm):
    class Meta:
        model = PrintSetting
        fields = '__all__'

Maintenance/templates/Maintenance/ticket_detail.html
{% extends 'base.html' %}
{% block body %}
    {% if not object.customer_received %}
        <div class="col-lg-12 dont-print">
            {% if object.status == 1 %}
                <a class="btn btn-success btn-block" href="{% url 'Maintenance:Diagnosis' object.id %}"
                   data-toggle="modal" data-target="#sub_modal"
                >
                    <i class="fa fa-screwdriver"></i>
                    تشخيص
                </a>
            {% endif %}
            {% if object.status == 2 %}
                <a class="btn btn-success btn-block" href="{% url 'Maintenance:CostRating' object.id %}"
                   data-toggle="modal"
                   data-target="#sub_modal">
                    <i class="fa fa-dollar-sign"></i>
                    تقييم
                </a>
            {% endif %}
            {% if object.status == 3 %}

            <a class="btn btn-success btn-block" href="{% url 'Maintenance:CustomerReply' object.id %}"
               data-toggle="modal"
               data-target="#sub_modal">
                <i class="fa fa-mobile"></i>
الاتصال بالعميل
            </a>

            {% endif %}
            {% if object.status == 4 or object.status == 5 or object.status == 7 or object.status == 8 %}
                <a class="btn btn-success btn-block" href="{% url 'Maintenance:CustomerReceived' object.id %}"
                   data-toggle="modal" data-target="#sub_modal">
                    <i class="fa fa-truck"></i>
                    تسليم العميل
                </a>
            {% endif %}
            {% if object.status == 6 %}

                <a class="btn btn-success btn-block" href="{% url 'Maintenance:TicketDone' object.id %}"
                   data-toggle="modal" data-target="#sub_modal">
                    <i class="fa fa-check-circle"></i>
                    تمت الصيانة
                </a>

            {% endif %}
        </div>
        <div class="col-lg-12 dont-print">
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-4">
                    <a href="{% url 'Maintenance:TransferTo' object.id %}" class="btn btn-block btn-warning"
                       data-toggle="modal" data-target="#sub_modal">
                        <i class="fa fa-forward"></i>
                        تحويل
                    </a>
                </div>
                {% if object.outsource_status == 1 %}
                    <div class="col-lg-4 col-md-4 col-sm-4">
                        <a href="{% url 'Maintenance:OutsourceTransfer' object.id %}" class="btn btn-block btn-info"
                           data-toggle="modal" data-target="#sub_modal">
                            <i class="fa fa-truck"></i>
                            تحويل إلي صيانة خارجية
                        </a>
                    </div>
                {% elif object.outsource_status == 2 %}
                    <div class="col-lg-4 col-md-4 col-sm-4">
                        <a href="{% url 'Maintenance:OutsourceReceived' object.id %}" class="btn btn-block bg-primary"
                           data-toggle="modal" data-target="#sub_modal">
                            <i class="fa fa-download"></i>
                            استلام من الصيانة الخارجية
                        </a>
                    </div>
                {% endif %}
                <div class="col-lg-4 col-md-4 col-sm-4">
                    <a href="{% url 'Maintenance:RejectTicket' object.id %}" class="btn btn-block btn-danger"
                       data-toggle="modal" data-target="#sub_modal">
                        <i class="fa fa-times-circle"></i>
                        لا يمكن إصلاح الجهاز
                    </a>
                </div>
            </div>
        </div>
    {% endif %}
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <img src="{% url 'Barcode:single_generator' object.id %}">
                <br>
                تذكرة صيانة رقم: {{ object.id }}
                <br>
                <a href="{% url 'Maintenance:print_receipt' object.id %}" class="btn-sm btn-info" target="_blank">
                    <i class="fa fa-receipt"></i>
                </a>
                <a href="{% url 'Barcode:print_barcode' %}?barcode={{ object.id }}&par1={{ object.customer.phone }}&par2={{ object.date.date.isoformat }}&quantity=1" class="btn-sm bg-primary" target="_blank">
                    <i class="fa fa-barcode"></i>
                </a>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
                        <i class="fa fa-user"></i>
                        اسم العميل
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
                        {{ object.customer.name }}
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
                        <i class="fa fa-mobile"></i>
                        رقم التليفون
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
                        <a href="tel:{{ object.customer.phone }}">
                            {{ object.customer.phone }}
                        </a>
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
                        <i class="fa fa-desktop"></i>
                        نوع الجهاز
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
                        {{ object.product }}
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
                        <i class="fa fa-barcode"></i>
                        سيريال الجهاز
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
                        {{ object.sn }}
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
                        <i class="fa fa-exclamation-triangle"></i>
                        المشكلة
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
                        {{ object.problem|linebreaks }}
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
                        <i class="fa fa-screwdriver"></i>
                        التشخيص
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
                        {{ object.diagnosis|linebreaks }}
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
                        <i class="fa fa-sticky-note"></i>
                        ملاحظات
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
                        {{ object.notes|linebreaks }}
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
                        <i class="fa fa-dollar-sign"></i>
                        التكلفة
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
                        {{ object.cost }}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <i class="fa fa-comments"></i> تحديثات التذكرة
                <a href="{% url 'Maintenance:TicketReplyCreate' object.id %}" class="btn-sm btn-info"
                   data-toggle="modal" data-target="#sub_modal">
                    <i class="fa fa-comment-dots"></i>
                </a>
            </div>
            <div class="card-body">
                {% for x in object.ticketreply_set.all %}
                    {% if request.user == x.employee %}
                        <div class="col-lg-12">
                            <div class="row">
                                <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
                                    {% if x.employee.avatar %}
                                        <img src="{{ x.employee.avatar.url }}" alt="{{ x.employee }}">
                                    {% else %}
                                        <i class="fa fa-user"></i>
                                        <br>
                                        {{ x.employee }}
                                    {% endif %}
                                </div>
                                <div class="col-lg-10 col-md-10 col-sm-10 col-xs-10">
                                    <div class="btn btn-primary btn-block">
                                        {{ x.reply|linebreaks }}
                                    </div>
                                    <small>
                                        <i class="fa fa-calendar"></i> {{ x.date.date.isoformat }}
                                        <i class="fa fa-clock"></i> {{ x.date.time }}
                                        {% if x.notify_customer %}
                                            <i class="fa fa-bell"></i>
                                            تم تنبيه العميل
                                        {% endif %}
                                    </small>
                                </div>
                            </div>
                        </div>
                    {% else %}
                        <div class="col-lg-12">
                            <div class="row">
                                <div class="col-lg-10 col-md-10 col-sm-10 col-xs-10">
                                    <div class="btn btn-info btn-block">
                                        {{ x.reply|linebreaks }}
                                    </div>
                                    <small>
                                        <i class="fa fa-calendar"></i> {{ x.date.date.isoformat }}
                                        <i class="fa fa-clock"></i> {{ x.date.time }}
                                        {% if x.notify_customer %}
                                            <i class="fa fa-bell"></i>
                                            تم تنبيه العميل
                                        {% endif %}
                                    </small>
                                </div>
                                <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
                                    {% if x.employee.avatar %}
                                        <img src="{{ x.employee.avatar.url }}" alt="{{ x.employee }}">
                                    {% else %}
                                        <i class="fa fa-user"></i>
                                        <br>
                                        {{ x.employee }}
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

Maintenance/templates/Maintenance/ticket_list.html
{% extends 'base.html' %}
{% block body %}
    <div class="col-lg-12">
        <a href="{% url 'Maintenance:TicketCreate' %}" class="btn btn-block btn-success" data-toggle="modal" data-target="#sub_modal">
            <i class="fa fa-plus-circle"></i> إضافة
        </a>
    </div>
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <i class="fa fa-list"></i>
                تذاكر الصيانة
            </div>
            <div class="card-body table-responsive">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <td>#</td>
                        <td>التاريخ</td>
                        <td>اسم العميل</td>
                        <td>موبايل</td>
                        <td>الجهاز</td>
                        <td>سيريال</td>
                        <td>الحالة</td>
                        <td>استلم</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>
                            <input type="number" name="id" placeholder="#">
                        </td>
                        <td>

                        </td>
                        <td>
                            <input type="text" name="customer_name" placeholder="اسم العميل" value="{{ request.GET.customer_name }}">
                        </td>
                        <td>
                            <input type="text" name="mobile" placeholder="موبايل" value="{{ request.GET.mobile }}">
                        </td>
                        <td>
                            <input type="text" name="device_barcode" placeholder="باركود" value="{{ request.GET.barcode }}">
                        </td>
                        <td>
                            <input type="text" name="serial" placeholder="سيريال" value="{{ request.GET.serial }}">
                        </td>
                        <td>
                            <select name="status">
                                <option value="0"{% if request.GET.status == 0 %} selected{% endif %}>جميع التذاكر</option>
                                <option value="1"{% if request.GET.status == 1 %} selected{% endif %}>قيد التشخيص</option>
                                <option value="2"{% if request.GET.status == 2 %} selected{% endif %}>قيد التقييم</option>
                                <option value="3"{% if request.GET.status == 3 %} selected{% endif %}>في انتظار رد العميل</option>
                                <option value="4"{% if request.GET.status == 4 %} selected{% endif %}>العميل يرفض التكلفة</option>
                                <option value="6"{% if request.GET.status == 6 %} selected{% endif %}>قيد الاصلاح</option>
                                <option value="7"{% if request.GET.status == 7 %} selected{% endif %}>تمت الصيانة</option>
                                <option value="8"{% if request.GET.status == 8 %} selected{% endif %}>لا يمكن إصلاح الجهاز</option>
                            </select>
                        </td>
                    <td></td>
                        <td>
                            <button class="btn btn-block bg-primary">
                                <i class="fa fa-search"></i>
                            </button>
                        </td>
                    </tr>
                    </thead>
                    <tbody>
                    {% for x in object_list %}
                        <tr>
                            <td>{{ x.id }}</td>
                            <td>{{ x.date.date.isoformat }}</td>
                            <td>{{ x.customer.name }}</td>
                            <td><a href="tel:{{ x.customer.phone }}">{{ x.customer.phone }}</a></td>
                            <td>{{ x.product }}</td>
                            <td>{{ x.sn }}</td>
                            <td>{{ x.get_status_display }}</td>
                            <td>
                                {% if x.customer_received %}
                                <i class="fa fa-check-circle"></i>
                                {% else %}
                                <i class="fa fa-minus-circle"></i>
                                {% endif %}
                            </td>
                            <td>
                                <a href="{% url 'Maintenance:TicketDetail' x.id %}" class="btn-sm btn-info">
                                    <i class="fa fa-eye"></i>
                                </a>
                                <a href="{% url 'Maintenance:TransferTo' x.id %}" class="btn-sm btn-warning"
                                data-toggle="modal" data-target="#sub_modal">
                                    <i class="fa fa-forward"></i>
                                </a>
                                <a href="{% url 'Maintenance:TicketDelete' x.id %}" class="btn-sm btn-danger"
                                data-toggle="modal" data-target="#sub_modal">
                                    <i class="fa fa-trash"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}